### ISSUE TITLE
naming of anon datatype

### ISSUE THREAD

**Issue by dev747368** [monoidic/go-api-parser#1]
I noticed that some data types are specified as ```package.structname.fieldname|[xx]arr[xx]```, where [xx] is the same value, repeated.

From a functional point of view, it seems like it won't matter as long as the reference to the data type has the same name, but it seems like its a bit fishy.

example:
```json
      "runtime.mheap": {
        "Fields": [
...
          {
            "Name": "central",
            "DataType": "runtime.mheap.central|[136]arr[136]"
          },
...
      "runtime.mheap.central|[136]arr": {
        "Fields": [
          {
            "Name": "mcentral",
            "DataType": "runtime.mcentral"
          },
          {
            "Name": "pad",
            "DataType": "byte[24]"
          }
        ]
      },
```

Is there a corner case that the extra ```|[xx]arr``` is needed to disambiguate the type?

**Comment by monoidic** [comment]
The preceding name should uniquely identify the array literal. It does appear to be redundant, yes. I will remove it.
As before, sorry for the late response.

**Comment by dev747368** [comment]
no problem.  I'm exploring generating names for anon structs / interfaces that will hopefully match the symbol names extracted from the rtti in compiled binaries, so this particular issue is mostly OBE.

**Comment by monoidic** [comment]
[Commit 16a4755](/monoidic/go-api-parser/commit/16a475587b47e47b10bbb6b6fb3d109adb1f7736) should address this.
