### ISSUE TITLE
panic when getting typename when compiled with go 1.23

### ISSUE THREAD

**Issue by dev747368** [monoidic/go-api-parser#2]
I'm getting this when built using 1.23:  (works fine when built with 1.22)
```
 ~/github/go-api-parser/go-api-parser -src ~/bin/golang/go-1.23/src/ -out ./golang_1.23.api.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x625fe9]

goroutine 69 [running]:
go/types.(*Package).Path(...)
        /home/me/bin/golang/go-1.23/src/go/types/package.go:34
main.getTypeName(...)
        /home/me/github/go-api-parser/parse.go:295
main.(*pkgData).getTypeName(0xc02695fdc0, {0x6eeb50?, 0xc000136140}, {0xc026973960?, 0x2?})
        /home/me/github/go-api-parser/parse.go:240 +0x1c9
main.(*pkgData).tupToSlice(0xc02695fdc0, 0xc005324990, {0xc0269710c8, 0x17})
        /home/me/github/go-api-parser/parse.go:196 +0x194
main.(*pkgData).parseFunc(0xc02695fdc0, 0xc0002e1e30?)
        /home/me/github/go-api-parser/parse.go:36 +0x9d
main.pkgExtract(0xc000084150, 0xc0000841c0, 0xc0000120d0)
        /home/me/github/go-api-parser/main.go:223 +0x27e
created by main.main in goroutine 1
        /home/me/github/go-api-parser/main.go:321 +0x4bd
```

I put a println() there to dump tn.Name() when tn.Pkg() is nil, and it shows "any" as the typename.

**Comment by monoidic** [comment]
Seems to be some change in the `go/types.Alias` type between Go 1.22 and 1.23? I already had `gotypesalias=1` set in `parse.go`
~~afaict, it's only an issue with `type any = interface{}`, so I'm just going to special-case it.~~
No, better solution soon™.
Sorry for the late response.

**Comment by dev747368** [comment]
No rush.  I have diverged from your code base a bit to meet some of my specific needs, and handling ```any``` got addressed.

**Comment by monoidic** [comment]
[Commit f7da307](/monoidic/go-api-parser/commit/f7da307d16ca0059f92520d5b56cbb9a85d62cd0) should address this.
